// Generated by CoffeeScript 1.3.3
(function() {
  var Stream, node, stream, username;

  Stream = (function() {

    function Stream(node, username) {}

    Stream.prototype.getTweets = function() {};

    return Stream;

  })();

  node = $('.stream').eq(0);

  username = 'mhluska';

  stream = new Stream(node, username);

  stream.getTweets();

}).call(this);
